export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Since 2018",
  headline: "Sari-sari Filipino Kitchen",
  description: "5/177 High Street, Christchurch Central City, Christchurch",
  buttonLabel: "Get Started",
  imgStart: false,
  img: require("../images/sari1.svg").default,
  alt: "Filipino Food",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Since 2018",
  headline: "Sari-sari Filipino Kitchen",
  description: "5/177 High Street, Christchurch Central City, Christchurch",
  buttonLabel: "Learn More",
  imgStart: true,
  img: require("../images/sari2.svg").default,
  alt: "Filipino Food",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: "signup",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Since 2018",
  headline: "Sari-sari Filipino Kitchen",
  description: "5/177 High Street, Christchurch Central City, Christchurch",
  buttonLabel: "Get Started",
  imgStart: true,
  img: require("../images/sari3.svg").default,
  alt: "Filipino Food",
  dark: true,
  primary: true,
  darkText: false,
};
